### ISSUE TITLE
If trying a theme like zenburn, some colors are wacky that aren't otherwise if installed.

### ISSUE THREAD

**Issue by rieje** [larstvei/Try#5]
I `try`ed the [zenburn theme](https://github.com/bbatsov/zenburn-emacs) and noticed that when I did an `M-x`, the highlighting of the text on the left side of the minibuffer is incorrect, but when I installed it, it's fine.

**Comment by larstvei** [comment]
Hi, thanks for reporting!

I tried to reproduce this, but I got the same result from `try`ing and installing. Do you have a minimal config where the bug is reproducible?

Two things you can check:
  - If you have multiple archives in `package-archive`, then `try` might have installed a different version.
  - In Emacs, themes must be explicitly disabled, so if you tried zenburn after trying/using some other theme, this might affect how it looks.

A side note on this last point: I think this is insane default behavior, and have fixed it in my own config with this snippet:
```emacs-lisp
(defadvice load-theme
    (before disable-before-load (theme &optional no-confirm no-enable) activate)
  (mapc 'disable-theme custom-enabled-themes))
```
